#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
from importlib import import_module
from functions.common import validateInput, getConfig

parser = argparse.ArgumentParser(description='manager script for ontolox-db rulesets')
parser.add_argument('-l', '--lang', nargs=1, help='language iso-639-1', metavar='language', dest='language')
parser.add_argument('-c', '--config', nargs=1, help='config file path', metavar='config', dest='config')
parser.add_argument('--dont-ask', help="asume yes at questions", action="store_true")
rules = parser.add_argument_group('rules')
rules.add_argument('--adjective-antonyms', help="find antonyms for adjective", action="store_true")
rules.add_argument('--adjective-material-nouns', help="find adjectives for material nouns", action="store_true")
rules.add_argument('--form-syllable-counts', help="find syllable count for forms", action="store_true")
rules.add_argument('--noun-components', nargs=1, help="init finding components in nouns", metavar="componentID", dest="noun_components")
rules.add_argument('--noun-components-refresh', help="walk all frequently used components and recheck", action="store_true")
rules.add_argument('--noun-components-find', help="find new nouns based on frequently used components", action="store_true")
rules.add_argument('--noun-components-senses', help="find new senses based on frequently used components", action="store_true")
rules.add_argument('--noun-diminutives', help="find diminuitives for nouns", action="store_true")
rules.add_argument('--noun-genders', help="find gender for noun forms", action="store_true")
rules.add_argument('--noun-genders-category', help="find gender for noun forms by category", action="store_true")
rules.add_argument('--noun-plurals', help="find plurals for canonical nouns", action="store_true")
rules.add_argument('--verb-related-nouns', help="find related nouns for verbs", action="store_true")
rules.add_argument('--verb-singulars', help="find remaing singular forms for verbs with a stem", action="store_true")
rules.add_argument('--verb-stems', help="find stems for verbs", action="store_true")


args = parser.parse_args()
argsdict = vars(args)
config = getConfig(argsdict)
language = validateInput(argsdict,"language",config["language"])
dont_ask = False

if args.dont_ask:
	dont_ask = True


# import language module
# check for language existence later
mod = import_module('rulesets.' + language)
Ruleset = getattr(mod, "Ruleset")
r = Ruleset(config,dont_ask)

if args.adjective_antonyms:
	r.adjectiveAntonyms()

if args.adjective_material_nouns:
	r.adjectiveMaterialNouns()

if args.form_syllable_counts:
	r.formSyllableCounts()

if args.noun_components:
	r.nounComponents(args.noun_components[0])

if args.noun_components_refresh:
	r.refreshComponents()

if args.noun_components_find:
	r.nounComponentsFind()

if args.noun_components_senses:
	r.nounComponentsSenses()

if args.noun_diminutives:
	r.nounDiminutives()

if args.noun_genders:
	r.nounGender()

if args.noun_genders_category:
	r.nounGenderCategory()

if args.noun_plurals:
	r.nounPlurals()

if args.verb_related_nouns:
	r.verbRelatedNouns()

if args.verb_singulars:
	r.verbSingulars()

if args.verb_stems:
	r.verbStems()
