#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
from importlib import import_module
from functions.common import validateInput, getConfig

parser = argparse.ArgumentParser(description='manager script for ontolox-db rulesets')
parser.add_argument('language', help="language key")
parser.add_argument('-c', '--config', nargs=1, help='config file path', metavar='config', dest='config')
parser.add_argument('--dont-ask', help="asume yes at questions", action="store_true")
rules = parser.add_argument_group('rules')
rules.add_argument('--adjective-antonyms', help="find antonyms for adjective", action="store_true")
rules.add_argument('--adjective-material-nouns', help="find adjectives for material nouns", action="store_true")
rules.add_argument('--noun-components', nargs=1, help="init finding components in nouns", metavar="componentID", dest="noun_components")
rules.add_argument('--noun-components-refresh', help="walk all frequently used components and recheck", action="store_true")
rules.add_argument('--noun-genders', help="find gender for noun forms", action="store_true")
rules.add_argument('--noun-plurals', help="find plurals for canonical nouns", action="store_true")
rules.add_argument('--verb-related-nouns', help="find related nouns for verbs", action="store_true")


args = parser.parse_args()
argsdict = vars(args)
config = getConfig(argsdict)
dont_ask = False

if args.dont_ask:
	dont_ask = True


# import language module
# check for language existence later
mod = import_module('rulesets.' + args.language)
Ruleset = getattr(mod, "Ruleset")
r = Ruleset(config,dont_ask)
r.getTopUsedComponents()
if args.adjective_antonyms:
	r.adjectiveAntonyms()

if args.adjective_material_nouns:
	r.adjectiveMaterialNouns()

if args.noun_components:
	r.nounComponents(args.noun_components[0])

if args.noun_components_refresh:
	r.refreshComponents()

if args.noun_genders:
	r.nounGender()

if args.noun_plurals:
	r.nounPlurals()

if args.verb_related_nouns:
	r.verbRelatedNouns()

